export const GAME_NAME_MAPPING: { [key: string]: string } = {
  callofduty: "Call of Duty",
  dota2: "Dota 2",
  counterstrike: "Counter-Strike",
  valorant: "VALORANT",
  mobilelegends: "Mobile Legends: Bang Bang",
  leagueoflegends: "League of Legends",
  rocketleague: "Rocket League",
  apexlegends: "Apex Legends",
  overwatch: "Overwatch",
  pubgmobile: "PUBG Mobile",
  rainbowsix: "Rainbow Six",
  fighters: "Fighting Games",
  starcraft2: "StarCraft 2",
  pubg: "PUBG: Battlegrounds",
  ageofempires: "Age of Empires",
  honorofkings: "Honor of Kings",
  smash: "Smash",
  brawlstars: "Brawl Stars",
  warcraft: "Warcraft",
  easportsfc: "EA SPORTS FC",
  starcraft: "StarCraft",
  wildrift: "Wild Rift",
  hearthstone: "Hearthstone",
  heroes: "Heroes of the Storm",
  artifact: "Artifact",
};
