name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Deploy to VPS with PM2
        run: pm2 restart liquipedia-scraper-api ||
          pm2 start dist/index.js --name liquipedia-scraper-api
