name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript project
        run: npm run build

      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Deploy to VPS with PM2
        run: |
          pm2 restart liquipedia-scraper-api || pm2 start dist/index.js --name liquipedia-scraper-api
